name: network-operations
functions:
- url: hub://aggregate:fix-describe
  name: aggregate
- url: hub://describe:fix-describe
  name: describe
- url: hub://feature_selection:fix-describe
  name: feature_selection
- url: hub://sklearn_classifier:fix-describe
  name: train
- url: hub://test_classifier:fix-describe
  name: test
- url: hub://model_server_tester:fix-describe
  name: model_server-tester
- url: hub://concept_drift:fix-describe
  name: concept_drift
- url: hub://stream_to_parquet:fix-describe
  name: s2p
- url: hub://virtual_drift:fix-describe
  name: virtual_drift
- url: /User/demo-network-operations/src/generator.yaml
  name: generator
- url: /User/demo-network-operations/src/preprocessor.yaml
  name: create_feature_vector
- url: /User/demo-network-operations/src/inference-server.yaml
  name: serving
- url: /User/demo-network-operations/src/labeled_stream_creator.yaml
  name: labeled_stream
workflows:
- name: main
  path: /User/demo-network-operations/src/workflow.py
artifacts:
- key: metrics
  kind: ''
  iter: 0
  tree: 28b6dc395cae0aa7efb5a5b041ca4f08256fc678
  target_path: /User/demo-network-operations/data/metrics.pq
  db_key: metrics
- key: lgb_configs
  kind: ''
  iter: 0
  tree: 28b6dc395cae0aa7efb5a5b041ca4f08256fc678
  target_path: /User/demo-network-operations/data/lgb_model.json
  db_key: lgb_configs
artifact_path: ''
